### ISSUE TITLE
pip install: Invalid script entry point: A callable suffix is required

### ISSUE THREAD

**Issue by yoursunny** [UCLA-IRL/ndn-hydra#12]
Steps to reproduce:

```shell
docker run --rm python:3.9 pip install ndn-hydra
```

Expected: installation succeeds

Actual: error message

```text
Installing collected packages: urllib3, pytz, pyparsing, pygtrie, pycryptodomex, MarkupSafe, idna, chardet, certifi, aenum, toml, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-jsmath, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, snowballstemmer, requests, PyYAML, python-ndn, Pygments, py, pluggy, packaging, Jinja2, iniconfig, imagesize, docutils, babel, attrs, alabaster, Sphinx, pytest, ndn-python-repo, sphinx-rtd-theme, sphinx-autodoc-typehints, ndn-svs, ndn-hydra
ERROR: For req: ndn-hydra. Invalid script entry point: <ExportEntry ndn-hydra-client = client.main.main.main:None []> - A callable suffix is required. Cf https://packaging.python.org/specifications/entry-points/#use-for-scripts for more information.
```

It seems that the published `ndn-hydra-0.1.0.tar.gz` file does not contain the source code for *client* component.

**Comment by justincpresley** [comment]
For now, I've updated the library to only include the repo part (not client). This is a temporary fix for the error as we should include the client as well.

**Comment by yoursunny** [comment]
I see commit 01b1b115d429c600bc4b5cde26bed44b89879e29 is deleting the client from being installed.
This implies that a user who installed the package via pip (following "instructions for use" in documentation) cannot fully use the package, because the client command is unavailable.
I think the client should be included in the package, or published as a separate package.

**Comment by yoursunny** [comment]
> This is a temporary fix for the error as we should include the client as well.

What's the obstacle in including the client components in the package?

**Comment by justincpresley** [comment]
No obstacle.
I just recently saw this issue. We need to re-organize how the code is laid out to effectively import packages properly.

**Comment by justincpresley** [comment]
See latest release. Let me know if you still have problems with importing.
