### ISSUE TITLE
ndn-hydra fails to start if ~/.ndn directory is deleted

### ISSUE THREAD

**Issue by yoursunny** [UCLA-IRL/ndn-hydra#14]
## Environment

* Linux kernel 5.4.0
* Docker `python:3.9` image
* NFD `0.7.1-30-ga103334b`, Unix socket mounted into the container at `/run/nfd.sock`
* NFD uses multicast strategy for all prefixes
* ndn-hydra 0.1.1 installed via pip
* ndn-hydra repository revision 01b1b115d429c600bc4b5cde26bed44b89879e29 cloned, for client scripts

## Steps to reproduce

```shell
root@2997f67aae11:/# rm -rf ~/.ndn
root@2997f67aae11:/# ndn-hydra -rp /hydra -n $(hostname -s) -s $RANDOM
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/site-packages/ndn_hydra/main/main.py", line 120, in run
    app = NDNApp()
  File "/usr/local/lib/python3.9/site-packages/ndn/app.py", line 63, in __init__
    self.keychain = default_keychain(config['pib'], config['tpm'])
  File "/usr/local/lib/python3.9/site-packages/ndn/client_conf.py", line 101, in default_keychain
    pib = KeychainSqlite3(os.path.join(pib_loc, 'pib.db'), tpm)
  File "/usr/local/lib/python3.9/site-packages/ndn/security/keychain/keychain_sqlite3.py", line 277, in __init__
    cursor = self.conn.execute('SELECT tpm_locator FROM tpmInfo')
sqlite3.OperationalError: no such table: tpmInfo
```

**Comment by yoursunny** [comment]
This issue persists in ndn-hydra-0.1.5

**Comment by justincpresley** [comment]
This will still be a concern in `v0.2.0`. However, I will include it in the next update. I will update this thread when progress has been made.

Note: We do plan on requiring an identity along with a key to start a repo node as all `hydra` nodes' first action will be to communicate with a NOC (WIP) to gain access to the desired system.

**Comment by yoursunny** [comment]
> We do plan on requiring an identity along with a key

You can require having a key, but this requirement needs to appear in the instructions.

**Comment by justincpresley** [comment]
See V0.2.1, Addresses this issue.
